name: Domain Check

on:
  # schedule:
  #   - cron: '0 * * * *'  # Run every hour
  workflow_dispatch:      # Allow manual triggers

jobs:
  check-domain:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Create config file
        run: echo "${{ secrets.CONFIG_INI }}" > config.ini
        
      - name: Run domain check
        run: python send_webhook.py
